# Generated by Django 5.1.15 on 2026-10-04 00:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0031_user_status_pending'),
        ('providers', '0002_provider_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('Turkcell', 'Turkcell'), ('Vodafone', 'Vodafone'), ('Avea', 'Türk Telekom'), ('Callback', 'دولي (Callback)')], max_length=10)),
                ('line_type', models.CharField(choices=[('Tam', 'رصيد ليرة (TL)'), ('Ses', 'باقات'), ('Sms', 'رسائل'), ('3gCep', 'إنترنت'), ('3gPc', 'إنترنت واي‑فاي / PC'), ('Yds', 'دولي'), ('BimCell', 'BiP (BimCell)'), ('Mtn', 'MTN سوري'), ('Syriatel', 'Syriatel سوري')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('logo_url', models.CharField(blank=True, default='', max_length=300)),
                ('is_query', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('passive', 'معطّل')], default='active', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontor_categories', to='core.tenant')),
            ],
            options={
                'db_table': 'kontor_categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KontorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('Turkcell', 'Turkcell'), ('Vodafone', 'Vodafone'), ('Avea', 'Türk Telekom'), ('Callback', 'دولي (Callback)')], max_length=10)),
                ('znet_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('details', models.CharField(blank=True, default='', max_length=300)),
                ('days', models.PositiveIntegerField(default=0)),
                ('gb', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('recommended_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('kind', models.CharField(choices=[('general', 'عامة'), ('offer', 'عرض')], default='general', max_length=8)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('passive', 'معطّل'), ('sale_paused', 'بيع موقوف مؤقتاً')], default='active', max_length=12)),
                ('provider_package_id', models.CharField(blank=True, default='', max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='kontor.kontorcategory')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontor_packages', to='providers.provider')),
                ('provider_alt1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontor_packages_alt1', to='providers.provider')),
                ('provider_alt2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontor_packages_alt2', to='providers.provider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontor_packages', to='core.tenant')),
            ],
            options={
                'db_table': 'kontor_packages',
                'ordering': ['operator', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='kontorcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'operator', 'line_type'), name='uniq_kontor_category'),
        ),
        migrations.AddConstraint(
            model_name='kontorpackage',
            constraint=models.UniqueConstraint(fields=('tenant', 'operator', 'znet_id'), name='uniq_kontor_package'),
        ),
    ]
