# Generated by Django 5.1.15 on 2026-10-04 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_status_pending'),
        ('kontor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KontorPriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontor_price_groups', to='core.tenant')),
            ],
            options={
                'db_table': 'kontor_price_groups',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KontorPackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margin_mode', models.CharField(blank=True, choices=[('percent', 'نسبة مئوية من الكلفة'), ('fixed', 'مبلغ ثابت فوق الكلفة')], default='', max_length=8)),
                ('margin_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('margin_round', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_prices', to='kontor.kontorpackage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontor_package_prices', to='core.tenant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='kontor.kontorpricegroup')),
            ],
            options={
                'db_table': 'kontor_package_prices',
                'constraints': [models.UniqueConstraint(fields=('package', 'group'), name='uniq_kontor_package_price')],
            },
        ),
        migrations.CreateModel(
            name='KontorDealerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('Turkcell', 'Turkcell'), ('Vodafone', 'Vodafone'), ('Avea', 'Türk Telekom'), ('Callback', 'دولي (Callback)')], max_length=10)),
                ('can_query', models.BooleanField(default=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontor_settings', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontor_dealer_settings', to='core.tenant')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_settings', to='kontor.kontorpricegroup')),
            ],
            options={
                'db_table': 'kontor_dealer_settings',
                'constraints': [models.UniqueConstraint(fields=('dealer', 'operator'), name='uniq_kontor_dealer_operator')],
            },
        ),
    ]
