# Generated by Django 5.1.15 on 2026-10-04 00:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_status_pending'),
        ('kontor', '0002_kontorpricegroup_kontorpackageprice_and_more'),
        ('providers', '0002_provider_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KontorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('Turkcell', 'Turkcell'), ('Vodafone', 'Vodafone'), ('Avea', 'Türk Telekom'), ('Callback', 'دولي (Callback)')], max_length=10)),
                ('gsm', models.CharField(max_length=15)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'قيد الإرسال'), ('processing', 'قيد التنفيذ'), ('success', 'نجح'), ('failed', 'فشل'), ('refunded', 'مُسترجَع')], default='pending', max_length=12)),
                ('tekil', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('provider_note', models.CharField(blank=True, default='', max_length=300)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kontor_orders', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='kontor.kontorpackage')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontor_orders', to='providers.provider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontor_orders', to='core.tenant')),
            ],
            options={
                'db_table': 'kontor_orders',
                'ordering': ['-id'],
            },
        ),
    ]
