# Generated by Django 5.1.15 on 2026-10-05 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_status_pending'),
        ('kontor', '0005_dealer_sell_price_short_names'),
        ('providers', '0002_provider_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kontororder',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='kontororder',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('dealer', 'client_uuid'), name='uniq_kontor_order_client_uuid_per_dealer'),
        ),
    ]
