# Generated by Django 5.1.15 on 2026-10-05 00:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill(apps, schema_editor):
    """
    ما قبل هذه الميزة: مزوّد ZNET واحد ضمنيّ لكل متجر. نجعله صريحاً كي لا يتغيّر شيء:
    كل باقة ⇐ مزوّدها الرئيسي هو ZNET المتجر، ومربوطة عنده برقمها وكلفتها؛
    واسم ZNET يُحفظ كما هو (فلا تُعدّ الأسماء الحالية «معدّلة»).
    """
    Package = apps.get_model("kontor", "KontorPackage")
    Link = apps.get_model("kontor", "KontorPackageLink")
    Provider = apps.get_model("providers", "Provider")
    znet = {}
    for prov in Provider.objects.all().order_by("id"):
        if ((prov.config or {}).get("code") or "").lower() == "znet":
            znet.setdefault(prov.tenant_id, prov)
    for p in Package.objects.all():
        p.provider_name = p.name
        fields = ["provider_name"]
        prov = znet.get(p.tenant_id)
        if prov is not None:
            if p.provider_id is None:
                p.provider_id = prov.id
                fields.append("provider")
            Link.objects.get_or_create(
                package_id=p.id, provider_id=prov.id,
                defaults={"tenant_id": p.tenant_id, "code": p.znet_id, "cost": p.provider_cost})
        p.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_status_pending'),
        ('kontor', '0007_link_code'),
        ('providers', '0002_provider_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontorSessionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, default='', max_length=200)),
                ('username', models.CharField(blank=True, default='', max_length=120)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('security_image', models.CharField(blank=True, default='D', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kontor_session_config',
            },
        ),
        migrations.AddField(
            model_name='kontorpackage',
            name='provider_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.CreateModel(
            name='KontorPackageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='kontor.kontorpackage')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontor_links', to='providers.provider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontor_links', to='core.tenant')),
            ],
            options={
                'db_table': 'kontor_package_links',
                'constraints': [models.UniqueConstraint(fields=('package', 'provider'), name='uniq_kontor_package_link')],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
