# Generated by Django 5.1.15 on 2026-10-06 21:14

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    Order = apps.get_model("kontor", "KontorOrder")
    for o in Order.objects.filter(package__isnull=False).select_related("package"):
        p = o.package
        Order.objects.filter(pk=o.pk).update(package_name=p.name, znet_id=p.znet_id, link_code=p.link_code)


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0008_providers_routing_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontororder',
            name='link_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='kontororder',
            name='package_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='kontororder',
            name='znet_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='kontororder',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='kontor.kontorpackage'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
