# Generated by Django 5.1.15 on 2026-10-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0009_order_package_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontorpackage',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
