# Generated by Django 5.1.15 on 2026-10-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_status_pending'),
        ('kontor', '0010_package_is_manual'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kontorcategory',
            name='uniq_kontor_category',
        ),
        migrations.AddField(
            model_name='kontorcategory',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='kontorcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_custom', False)), fields=('tenant', 'operator', 'line_type'), name='uniq_kontor_category'),
        ),
    ]
