# Generated by Django 5.1.15 on 2026-10-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0011_category_is_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontorLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('operator', 'شركة الرقم'), ('offers', 'العروض')], max_length=10)),
                ('gsm', models.CharField(max_length=15)),
                ('operator', models.CharField(blank=True, default='', max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kontor_lookup_cache',
                'constraints': [models.UniqueConstraint(fields=('kind', 'gsm', 'operator'), name='uniq_kontor_lookup')],
            },
        ),
    ]
