# Generated by Django 5.1.15 on 2026-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0012_lookup_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontororder',
            name='trace',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
