# Generated by Django 5.1.15 on 2026-10-09 21:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_buyer_price(apps, schema_editor):
    """قبل الوسيط كان ما دفعه الوكيل هو ما قبضه المتجر."""
    KontorOrder = apps.get_model("kontor", "KontorOrder")
    KontorOrder.objects.filter(buyer_price=0).update(buyer_price=models.F("sell_price"))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_margin_round'),
        ('core', '0031_user_status_pending'),
        ('kontor', '0013_order_trace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kontororder',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_kontor_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kontororder',
            name='agent_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='kontororder',
            name='buyer_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.CreateModel(
            name='AgentKontorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontor_prices', to='catalog.agentpricegroup')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_prices', to='kontor.kontorpackage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_kontor_prices', to='core.tenant')),
            ],
            options={
                'db_table': 'kontor_agent_prices',
                'constraints': [models.UniqueConstraint(fields=('group', 'package'), name='uniq_agent_kontor_price')],
            },
        ),
        migrations.RunPython(backfill_buyer_price, migrations.RunPython.noop),
    ]
