# Generated by Django 5.1.15 on 2026-10-09 22:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0015_agent_price_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentkontorprice',
            name='margin_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='agentkontorprice',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='kontororder',
            name='agent_profit',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='kontororder',
            name='balance_after',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='kontororder',
            name='balance_before',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='kontororder',
            name='buyer_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='kontororder',
            name='dealer_profit',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='kontororder',
            name='dealer_sell_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16),
        ),
    ]
