# Generated by Django 5.1.15 on 2026-10-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0016_ledger_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontororder',
            name='busy_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
