# Generated by Django 5.1.15 on 2026-10-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0017_busy_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontororder',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
