# Generated by Django 5.1.15 on 2026-10-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_amount_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='margin_round',
            field=models.BooleanField(default=False),
        ),
    ]
