# Generated by Django 5.1.15 on 2026-10-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_margin_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproductprice',
            name='margin_mode',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='agentproductprice',
            name='margin_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentproductprice',
            name='margin_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
