# Generated by Django 5.1.15 on 2026-10-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_agent_price_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproductprice',
            name='margin_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='agentproductprice',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
