# Generated by Django 5.1.15 on 2026-10-10 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_ledger_precision'),
        ('core', '0034_login_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentpricegroup',
            name='uniq_agent_group_name',
        ),
        migrations.AddField(
            model_name='agentpricegroup',
            name='section',
            field=models.CharField(choices=[('games', 'الألعاب'), ('mobile', 'الرصيد (الموبايل)')], default='games', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='agentpricegroup',
            constraint=models.UniqueConstraint(fields=('agent', 'section', 'name'), name='uniq_agent_group_section_name'),
        ),
    ]
