"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-#-k4)5mucg1$@%6f(*g&ud+7q$pd4u$m3550zj4939-y2o*0zz",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "1") == "1"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# خلف Caddy: العنوان الحقيقي والبروتوكول يصلان في ترويستين. بدون هذا يظنّ
# Django كل اتصال غير مشفّر، فيعيد التوجيه إلى https إلى ما لا نهاية.
# نطاق المنصّة — منه يُبنى عنوان كل متجر (`islam.wtn4.com`). كان مكتوباً
# `example.com` في الواجهة، فظهرت العناوين كلّها خاطئة بلا أن ينبّه أحد.
PLATFORM_DOMAIN = os.environ.get("PLATFORM_DOMAIN", "wtn4.com")

# كل متجرٍ عنوانٌ جديد (`islam.wtn4.com`) — ولا نعود إلى ملفّ البيئة عند كل
# متجر. النقطة البادئة تعني «هذا النطاق وما تحته»، فتُضاف هنا لا في `.env`:
# قائمةٌ يدوية تُنسى، والنسيان يظهر بـ 400 لا تقول أن الاسم هو السبب.
_wildcard = f".{PLATFORM_DOMAIN}"
if "*" not in ALLOWED_HOSTS and _wildcard not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_wildcard)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party
    "rest_framework",
    "corsheaders",
    # local apps
    "core",
    "catalog",
    "providers",
    "orders",
    "pool",
    "payments",
    "superadmin",
    "agent",
    "whatsapp",
    "inventory",
    "clientapi",
    "kontor",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # يستنتج المتجر من العنوان قبل أي شيء آخر — قبل WhiteNoise عمداً: عنوانٌ
    # لا متجر له لا يقدَّم منه ملفّ واحد.
    "core.middleware.StoreHostMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# A single DATABASE_URL (Neon, Supabase, …) takes precedence when set, so a
# managed Postgres can be swapped in from the host dashboard alone. Any stale
# DB_* variables left behind by a previous provider are ignored in that case.
# Without it we fall back to the discrete DB_* variables used locally.
_DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if _DATABASE_URL:
    _url = urlparse(_DATABASE_URL)
    _options = {k: v[-1] for k, v in parse_qs(_url.query).items()}
    # A remote Postgres is reached over the public internet — never in the
    # clear. `setdefault`, not an override: a database on the same Docker
    # bridge says `?sslmode=disable` in its URL and means it.
    _options.setdefault("sslmode", "require")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(_url.path).lstrip("/"),
            "USER": unquote(_url.username or ""),
            "PASSWORD": unquote(_url.password or ""),
            "HOST": _url.hostname or "",
            "PORT": str(_url.port or ""),
            "OPTIONS": _options,
            # The database lives outside the host now, so a fresh TCP+TLS
            # handshake per request is pure latency. Reuse connections, and
            # health-check them since serverless Postgres drops idle ones.
            "CONN_MAX_AGE": 600,
            "CONN_HEALTH_CHECKS": True,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "wtn_db"),
            "USER": os.environ.get("DB_USER", "wtn"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "wtn_dev_pass"),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }

# Custom user model (login by login_id)
AUTH_USER_MODEL = "core.User"

# Django REST Framework + JWT
REST_FRAMEWORK = {
    # JWT المعتاد، وفوقه شرطٌ واحد: توكن متجرٍ لا يفتح متجراً آخر (core/auth.py)
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.auth.StoreBoundJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # حدّ نداءات الواجهة الخارجية (clientapi) — كبحُ حلقةٍ مجنونة عند عميل
    # خارجي، لا حاجز أمني. الذاكرة المؤقّتة محليّة لكل عامل gunicorn فالحدّ
    # الفعلي مضاعف؛ الحاجز الحقيقي هو المحفظة والحدّ الائتماني.
    "DEFAULT_THROTTLE_RATES": {"client_api": "240/min"},
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# CORS (dev: allow the Vite frontend)
# الواجهة والـ API على **أصل واحد** (Django يقدّمهما معاً)، فلا متصفّح يعبر
# أصلاً. وعملاء الواجهة الخارجية خوادمُ لا متصفّحات فلا يمسّهم CORS.
# فتُفتح للجميع في التطوير وحده — وكانت مفتوحةً في الإنتاج بتعليق «dev only».
CORS_ALLOW_ALL_ORIGINS = DEBUG


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ar"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# الواجهة المبنية (Vite) — تُقدَّم من نفس أصل الخلفية في الإنتاج
FRONTEND_DIST = Path(
    os.environ.get("FRONTEND_DIST", BASE_DIR.parent / "frontend" / "dist")
)
if FRONTEND_DIST.is_dir():
    # WhiteNoise يقدّم أصول الواجهة (/assets/...) مباشرةً من الجذر
    WHITENOISE_ROOT = str(FRONTEND_DIST)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
