# Generated by Django 5.1.15 on 2026-10-09 22:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agent_profit',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='balance_after',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='balance_before',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='dealer_profit',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='dealer_sell_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16),
        ),
    ]
