# Generated by Django 5.1.15 on 2026-10-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ledger_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='busy_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
