# Generated by Django 5.1.15 on 2026-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentnotification_admin_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethodfield",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "نص قصير"),
                    ("number", "رقم"),
                    ("textarea", "نص طويل"),
                    ("select", "قائمة اختيار"),
                    ("image", "صورة (رفع من الجهاز)"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
