# Generated by Django 5.1.15 on 2026-10-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentmethodfield_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='currency',
            field=models.CharField(choices=[('TRY', 'ليرة تركية'), ('USD', 'دولار أمريكي'), ('SYP', 'ليرة سورية'), ('EUR', 'يورو'), ('SAR', 'ريال سعودي'), ('AED', 'درهم إماراتي'), ('EGP', 'جنيه مصري'), ('ANY', 'يحددها العميل')], default='TRY', max_length=8),
        ),
    ]
