# Generated by Django 5.1.15 on 2026-10-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethod_currency_any'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='qr_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
