# Generated by Django 5.1.15 on 2026-10-09 22:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='credit_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='receivingaccount',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
    ]
