# Generated by Django 5.1.15 on 2026-10-09 22:49

from django.db import migrations, models


# بيانات الحركات القديمة بين الوكيل الكبير ودكاكينه — تُعرف من بيانها
AGENT_SIDE = ("بيع ", "ردّ لدكانه", "تحويل إلى ", "سحب من ", "إيداع ", "إبطال إيداع ")
SHOP_SIDE = ("شحن من وكيلك", "سحب لصالح وكيلك")


def backfill(apps, schema_editor):
    from django.db.models import Q
    Txn = apps.get_model("core", "WalletTransaction")
    agent_q = Q()
    for p in AGENT_SIDE:
        agent_q |= Q(note__startswith=p)
    Txn.objects.filter(agent_q, wallet__user__role="ana_bayi").update(internal=True)
    shop_q = Q()
    for p in SHOP_SIDE:
        shop_q |= Q(note__startswith=p)
    Txn.objects.filter(shop_q, wallet__user__parent__role="ana_bayi").update(internal=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_ledger_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='internal',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
