# Generated by Django 5.1.15 on 2026-10-10 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_agent_group_sections'),
        ('core', '0034_login_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_kontor_price_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontor_dealers', to='catalog.agentpricegroup'),
        ),
    ]
